### ISSUE TITLE
I can't connect to Substrate 2.0.0-rc4

### ISSUE THREAD

**Issue by yangwao** [staketechnologies/ink-playground#25]
Hello, are there any plans to update API?

So far, it doesn't work :/

![image](https://user-images.githubusercontent.com/5887929/90407872-4df0ac00-e0a7-11ea-859c-6cd2dad93057.png)

**Comment by taskooh** [comment]
https://github.com/staketechnologies/ink-playground/pull/27
Working now!
Thanks for the issue.
